-- ================================================================
-- 04 TPC-H RETAIL & SUPPLY CHAIN: Beginner to Advanced
-- ================================================================
-- Uses: SNOWFLAKE_SAMPLE_DATA.TPCH_SF1 (1GB scale factor)
-- A complete progression through a star-schema supply chain dataset.
-- ================================================================

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- LEVEL 1: BEGINNER – Explore the schema
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- 1.1 What tables exist?
SELECT TABLE_NAME, ROW_COUNT, COMMENT
FROM SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'TPCH_SF1'
ORDER BY ROW_COUNT DESC;

-- 1.2 Preview each dimension
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION   LIMIT 5;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION   LIMIT 10;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER LIMIT 10;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER LIMIT 10;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART     LIMIT 10;

-- 1.3 Preview fact tables
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS   LIMIT 10;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LIMIT 10;

-- 1.4 Basic counts
SELECT COUNT(*) AS TOTAL_CUSTOMERS  FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
SELECT COUNT(*) AS TOTAL_ORDERS     FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
SELECT COUNT(*) AS TOTAL_LINE_ITEMS FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

-- 1.5 Orders by status
SELECT O_ORDERSTATUS, COUNT(*) AS CNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
GROUP BY O_ORDERSTATUS;

-- 1.6 Orders by priority
SELECT O_ORDERPRIORITY, COUNT(*) AS CNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
GROUP BY O_ORDERPRIORITY
ORDER BY CNT DESC;


-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- LEVEL 2: INTERMEDIATE – JOINs and Aggregations
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- 2.1 Revenue by nation (customer's nation)
SELECT
    n.N_NAME AS NATION,
    COUNT(DISTINCT o.O_ORDERKEY) AS ORDER_COUNT,
    ROUND(SUM(o.O_TOTALPRICE), 2) AS TOTAL_REVENUE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
GROUP BY n.N_NAME
ORDER BY TOTAL_REVENUE DESC;

-- 2.2 Revenue by region
SELECT
    r.R_NAME AS REGION,
    COUNT(DISTINCT o.O_ORDERKEY) AS ORDER_COUNT,
    ROUND(SUM(o.O_TOTALPRICE), 2) AS TOTAL_REVENUE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
GROUP BY r.R_NAME
ORDER BY TOTAL_REVENUE DESC;

-- 2.3 Top 20 customers by lifetime spend
SELECT
    c.C_NAME,
    n.N_NAME AS NATION,
    COUNT(o.O_ORDERKEY) AS ORDER_COUNT,
    ROUND(SUM(o.O_TOTALPRICE), 2) AS LIFETIME_SPEND
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
GROUP BY c.C_NAME, n.N_NAME
ORDER BY LIFETIME_SPEND DESC
LIMIT 20;

-- 2.4 Top parts by total quantity sold
SELECT
    p.P_NAME,
    p.P_TYPE,
    p.P_SIZE,
    SUM(l.L_QUANTITY) AS TOTAL_QTY,
    ROUND(SUM(l.L_EXTENDEDPRICE), 2) AS TOTAL_REVENUE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART p ON l.L_PARTKEY = p.P_PARTKEY
GROUP BY p.P_NAME, p.P_TYPE, p.P_SIZE
ORDER BY TOTAL_REVENUE DESC
LIMIT 20;

-- 2.5 Supplier performance – average delivery time
SELECT
    s.S_NAME,
    n.N_NAME AS NATION,
    COUNT(*) AS ITEMS_SHIPPED,
    ROUND(AVG(DATEDIFF('day', l.L_SHIPDATE, l.L_RECEIPTDATE)), 1) AS AVG_DELIVERY_DAYS
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER s ON l.L_SUPPKEY = s.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON s.S_NATIONKEY = n.N_NATIONKEY
WHERE l.L_RECEIPTDATE IS NOT NULL
GROUP BY s.S_NAME, n.N_NAME
ORDER BY ITEMS_SHIPPED DESC
LIMIT 20;

-- 2.6 Monthly order trends
SELECT
    DATE_TRUNC('month', O_ORDERDATE) AS ORDER_MONTH,
    COUNT(*) AS ORDER_COUNT,
    ROUND(SUM(O_TOTALPRICE), 2) AS MONTHLY_REVENUE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
GROUP BY ORDER_MONTH
ORDER BY ORDER_MONTH;


-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- LEVEL 3: ADVANCED – Window functions, CTEs, analytics
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- 3.1 Revenue ranking by nation with running total
SELECT
    n.N_NAME AS NATION,
    ROUND(SUM(o.O_TOTALPRICE), 2) AS REVENUE,
    RANK() OVER (ORDER BY SUM(o.O_TOTALPRICE) DESC) AS REVENUE_RANK,
    ROUND(SUM(SUM(o.O_TOTALPRICE)) OVER (ORDER BY SUM(o.O_TOTALPRICE) DESC
        ROWS UNBOUNDED PRECEDING), 2) AS CUMULATIVE_REVENUE,
    ROUND(SUM(o.O_TOTALPRICE) / SUM(SUM(o.O_TOTALPRICE)) OVER () * 100, 2) AS PCT_OF_TOTAL
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
GROUP BY n.N_NAME
ORDER BY REVENUE DESC;

-- 3.2 Month-over-month revenue growth
WITH monthly AS (
    SELECT
        DATE_TRUNC('month', O_ORDERDATE) AS MONTH,
        SUM(O_TOTALPRICE) AS REVENUE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
    GROUP BY MONTH
)
SELECT
    MONTH,
    ROUND(REVENUE, 2) AS REVENUE,
    ROUND(LAG(REVENUE) OVER (ORDER BY MONTH), 2) AS PREV_MONTH,
    ROUND((REVENUE - LAG(REVENUE) OVER (ORDER BY MONTH))
        / NULLIF(LAG(REVENUE) OVER (ORDER BY MONTH), 0) * 100, 2) AS MOM_GROWTH_PCT
FROM monthly
ORDER BY MONTH;

-- 3.3 Customer segmentation (RFM-style)
WITH customer_metrics AS (
    SELECT
        c.C_CUSTKEY,
        c.C_NAME,
        n.N_NAME AS NATION,
        COUNT(o.O_ORDERKEY) AS FREQUENCY,
        ROUND(SUM(o.O_TOTALPRICE), 2) AS MONETARY,
        MAX(o.O_ORDERDATE) AS LAST_ORDER_DATE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
    GROUP BY c.C_CUSTKEY, c.C_NAME, n.N_NAME
)
SELECT
    C_NAME,
    NATION,
    FREQUENCY,
    MONETARY,
    NTILE(4) OVER (ORDER BY FREQUENCY)  AS FREQ_QUARTILE,
    NTILE(4) OVER (ORDER BY MONETARY)   AS SPEND_QUARTILE,
    CASE
        WHEN NTILE(4) OVER (ORDER BY FREQUENCY) = 4
         AND NTILE(4) OVER (ORDER BY MONETARY) = 4 THEN 'CHAMPION'
        WHEN NTILE(4) OVER (ORDER BY MONETARY) = 4 THEN 'HIGH_VALUE'
        WHEN NTILE(4) OVER (ORDER BY FREQUENCY) = 4 THEN 'LOYAL'
        WHEN NTILE(4) OVER (ORDER BY FREQUENCY) = 1
         AND NTILE(4) OVER (ORDER BY MONETARY) = 1 THEN 'AT_RISK'
        ELSE 'REGULAR'
    END AS SEGMENT
FROM customer_metrics
ORDER BY MONETARY DESC
LIMIT 50;

-- 3.4 Supplier concentration risk – Herfindahl index by part type
WITH supplier_share AS (
    SELECT
        p.P_TYPE,
        s.S_SUPPKEY,
        SUM(l.L_EXTENDEDPRICE) AS SUPPLIER_REVENUE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART p ON l.L_PARTKEY = p.P_PARTKEY
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER s ON l.L_SUPPKEY = s.S_SUPPKEY
    GROUP BY p.P_TYPE, s.S_SUPPKEY
),
market_share AS (
    SELECT
        P_TYPE,
        S_SUPPKEY,
        SUPPLIER_REVENUE,
        SUPPLIER_REVENUE / SUM(SUPPLIER_REVENUE) OVER (PARTITION BY P_TYPE) AS SHARE
    FROM supplier_share
)
SELECT
    P_TYPE,
    COUNT(DISTINCT S_SUPPKEY) AS SUPPLIER_COUNT,
    ROUND(SUM(SHARE * SHARE) * 10000, 0) AS HHI_INDEX,
    CASE
        WHEN SUM(SHARE * SHARE) * 10000 > 2500 THEN 'HIGH_CONCENTRATION'
        WHEN SUM(SHARE * SHARE) * 10000 > 1500 THEN 'MODERATE_CONCENTRATION'
        ELSE 'COMPETITIVE'
    END AS MARKET_STRUCTURE
FROM market_share
GROUP BY P_TYPE
ORDER BY HHI_INDEX DESC
LIMIT 20;

-- 3.5 Late shipment analysis with return rate correlation
WITH shipments AS (
    SELECT
        l.L_ORDERKEY,
        l.L_SUPPKEY,
        l.L_PARTKEY,
        l.L_EXTENDEDPRICE,
        l.L_RETURNFLAG,
        DATEDIFF('day', l.L_COMMITDATE, l.L_SHIPDATE) AS DAYS_LATE,
        CASE WHEN l.L_SHIPDATE > l.L_COMMITDATE THEN 1 ELSE 0 END AS IS_LATE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l
)
SELECT
    s.S_NAME,
    n.N_NAME AS SUPPLIER_NATION,
    COUNT(*) AS TOTAL_SHIPMENTS,
    SUM(sh.IS_LATE) AS LATE_SHIPMENTS,
    ROUND(SUM(sh.IS_LATE) / COUNT(*) * 100, 2) AS LATE_PCT,
    SUM(CASE WHEN sh.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) AS RETURNS,
    ROUND(SUM(CASE WHEN sh.L_RETURNFLAG = 'R' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2)
        AS RETURN_PCT
FROM shipments sh
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER s ON sh.L_SUPPKEY = s.S_SUPPKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON s.S_NATIONKEY = n.N_NATIONKEY
GROUP BY s.S_NAME, n.N_NAME
HAVING COUNT(*) > 100
ORDER BY LATE_PCT DESC
LIMIT 20;

-- 3.6 Year-over-year revenue by region with growth classification
WITH yearly_region AS (
    SELECT
        r.R_NAME AS REGION,
        YEAR(o.O_ORDERDATE) AS YEAR,
        SUM(o.O_TOTALPRICE) AS REVENUE
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
    JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY
    GROUP BY r.R_NAME, YEAR(o.O_ORDERDATE)
)
SELECT
    REGION,
    YEAR,
    ROUND(REVENUE, 2) AS REVENUE,
    ROUND(LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR), 2) AS PREV_YEAR_REVENUE,
    ROUND((REVENUE - LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR))
        / NULLIF(LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR), 0) * 100, 2)
        AS YOY_GROWTH_PCT,
    CASE
        WHEN (REVENUE - LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR))
            / NULLIF(LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR), 0) > 0.05
            THEN 'ACCELERATING'
        WHEN (REVENUE - LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR))
            / NULLIF(LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR), 0) > 0
            THEN 'GROWING'
        WHEN (REVENUE - LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR))
            / NULLIF(LAG(REVENUE) OVER (PARTITION BY REGION ORDER BY YEAR), 0) > -0.05
            THEN 'FLAT'
        ELSE 'DECLINING'
    END AS GROWTH_CLASS
FROM yearly_region
ORDER BY REGION, YEAR;
