-- =============================================================
-- 03_verify_public_data.sql
-- Verify the free public datasets the app depends on are
-- accessible.  Run this as a health check.
-- =============================================================

-- Check that the shared database exists
SHOW DATABASES LIKE 'SNOWFLAKE_PUBLIC_DATA_FREE';

-- Verify key tables the app queries
SELECT 'EMPLOYMENT_TIMESERIES' AS SOURCE, COUNT(*) AS ROW_COUNT
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_EMPLOYMENT_TIMESERIES
UNION ALL
SELECT 'PRICE_TIMESERIES', COUNT(*)
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_PRICE_TIMESERIES
UNION ALL
SELECT 'HOUSE_PRICE_TIMESERIES', COUNT(*)
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FHFA_HOUSE_PRICE_TIMESERIES
UNION ALL
SELECT 'COMPANY_INDEX', COUNT(*)
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.COMPANY_INDEX
UNION ALL
SELECT 'GEOGRAPHY_INDEX', COUNT(*)
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.GEOGRAPHY_INDEX;

-- Latest data dates (freshness check)
SELECT 'Employment' AS DOMAIN, MAX(DATE) AS LATEST_DATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_EMPLOYMENT_TIMESERIES
UNION ALL
SELECT 'CPI', MAX(DATE)
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_PRICE_TIMESERIES
UNION ALL
SELECT 'Housing', MAX(DATE)
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FHFA_HOUSE_PRICE_TIMESERIES;
