-- =============================================================
-- 04_analytical_views.sql
-- Pre-built analytical views the app and AI chat can query
-- for cross-domain insights and correlation analysis.
-- =============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE HACKDAYS_APP_DB;
USE SCHEMA APP_DATA;

-- Monthly national unemployment average
CREATE OR REPLACE VIEW V_MONTHLY_UNEMPLOYMENT AS
SELECT
    t.DATE,
    ROUND(AVG(t.VALUE * 100), 2) AS AVG_UNEMPLOYMENT_RATE,
    COUNT(DISTINCT g.GEO_NAME) AS STATES_REPORTING,
    ROUND(MAX(t.VALUE * 100), 2) AS MAX_STATE_RATE,
    ROUND(MIN(t.VALUE * 100), 2) AS MIN_STATE_RATE
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_EMPLOYMENT_TIMESERIES t
JOIN SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.GEOGRAPHY_INDEX g ON t.GEO_ID = g.GEO_ID
WHERE g.LEVEL = 'State'
  AND t.VARIABLE = 'Local_Area_Unemployment:_Unemployment_Rate,_Seasonally_adjusted,_Monthly'
  AND t.VALUE IS NOT NULL
GROUP BY t.DATE;

-- Monthly CPI headline + categories
CREATE OR REPLACE VIEW V_MONTHLY_CPI AS
SELECT
    DATE,
    MAX(CASE WHEN VARIABLE = 'CPI:_All_items,_Seasonally_adjusted,_Monthly' THEN VALUE END) AS CPI_ALL_ITEMS,
    MAX(CASE WHEN VARIABLE = 'CPI:_Food,_Seasonally_adjusted,_Monthly' THEN VALUE END) AS CPI_FOOD,
    MAX(CASE WHEN VARIABLE = 'CPI:_Energy,_Seasonally_adjusted,_Monthly' THEN VALUE END) AS CPI_ENERGY,
    MAX(CASE WHEN VARIABLE = 'CPI:_Shelter,_Seasonally_adjusted,_Monthly' THEN VALUE END) AS CPI_SHELTER
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.BUREAU_OF_LABOR_STATISTICS_PRICE_TIMESERIES
WHERE GEO_ID = 'country/USA'
  AND VALUE IS NOT NULL
GROUP BY DATE;

-- Monthly HPI
CREATE OR REPLACE VIEW V_MONTHLY_HPI AS
SELECT
    DATE,
    VALUE AS HPI_INDEX
FROM SNOWFLAKE_PUBLIC_DATA_FREE.PUBLIC_DATA_FREE.FHFA_HOUSE_PRICE_TIMESERIES
WHERE GEO_ID = 'country/USA'
  AND VARIABLE = 'FHFA_HPI_traditional_purchase-only_monthly_SA'
  AND VALUE IS NOT NULL;

-- Cross-domain monthly macro summary (joins unemployment, CPI, HPI)
CREATE OR REPLACE VIEW V_MACRO_MONTHLY_SUMMARY AS
SELECT
    u.DATE,
    u.AVG_UNEMPLOYMENT_RATE,
    u.MAX_STATE_RATE   AS WORST_STATE_UNEMPLOYMENT,
    u.MIN_STATE_RATE   AS BEST_STATE_UNEMPLOYMENT,
    c.CPI_ALL_ITEMS,
    c.CPI_FOOD,
    c.CPI_ENERGY,
    c.CPI_SHELTER,
    h.HPI_INDEX,
    -- YoY calculations
    ROUND(((c.CPI_ALL_ITEMS - LAG(c.CPI_ALL_ITEMS, 12) OVER (ORDER BY u.DATE))
        / NULLIF(LAG(c.CPI_ALL_ITEMS, 12) OVER (ORDER BY u.DATE), 0)) * 100, 2)
        AS CPI_YOY_PCT,
    ROUND(((h.HPI_INDEX - LAG(h.HPI_INDEX, 12) OVER (ORDER BY u.DATE))
        / NULLIF(LAG(h.HPI_INDEX, 12) OVER (ORDER BY u.DATE), 0)) * 100, 2)
        AS HPI_YOY_PCT
FROM V_MONTHLY_UNEMPLOYMENT u
LEFT JOIN V_MONTHLY_CPI c ON u.DATE = c.DATE
LEFT JOIN V_MONTHLY_HPI h ON u.DATE = h.DATE
ORDER BY u.DATE;
